language: c

sudo: required
dist: trusty

os:
  - linux
  - osx

env:
  global:
    - MAKEFLAGS="-j5"
    - EIO_MONITOR_POLL=1
  matrix:
    -
    - DISTRO=Ubuntu1804
    - DISTRO=Fedora28 CI_BUILD_TYPE=wayland
    - DISTRO=Fedora28 CI_BUILD_TYPE=misc
    - DISTRO=Fedora28 CI_BUILD_TYPE=misc-disabled
    - DISTRO=Fedora28 CI_BUILD_TYPE=release-ready
    - DISTRO=Debian91
    - DISTRO=Archlinux

services:
  - docker

matrix:
  fast_finish: true
  exclude:
    - os: osx
      env:
        DISTRO=Ubuntu1804
    - os: osx
      env:
        DISTRO=Fedora28
        CI_BUILD_TYPE=wayland
    - os: osx
      env:
        DISTRO=Fedora28
        CI_BUILD_TYPE=misc
    - os: osx
      env:
        DISTRO=Fedora28
        CI_BUILD_TYPE=misc-disabled
    - os: osx
      env:
        DISTRO=Fedora28
        CI_BUILD_TYPE=release-ready
    - os: osx
      env:
        DISTRO=Debian91
    - os: osx
      env:
        DISTRO=Archlinux

    - os: linux
      env:
  allow_failures:
    - os: linux
      env: DISTRO=Fedora28 CI_BUILD_TYPE=release-ready

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then .ci/ci-osx-deps.sh ; fi

before_script:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$DISTRO" != "" ]]; then
        docker pull stefanschmidt1/ci-support-files:$DISTRO
      fi
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
        docker version
        docker run --cidfile $HOME/cid -t -d -v `pwd`:/src -w /src stefanschmidt1/ci-support-files:$DISTRO bash
        cat $HOME/cid
      fi

script:
  - .ci/ci-configure.sh "$CI_BUILD_TYPE"
  - .ci/ci-make.sh "$CI_BUILD_TYPE"
  - .ci/ci-make-checkbuild.sh "$CI_BUILD_TYPE"
  - .ci/ci-make-examples.sh "$CI_BUILD_TYPE"
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CI_BUILD_TYPE" == "" ]]; then
          .ci/ci-make-benchmark.sh "$CI_BUILD_TYPE"
      fi
  - .ci/ci-make-install.sh "$CI_BUILD_TYPE"
  - .ci/ci-make-distcheck.sh "$CI_BUILD_TYPE"
  - |
      if [[ "$DISTRO" == "" ]] && [[ "$TRAVIS_OS_NAME" != "linux" ]] ; then
        .ci/build-efl-app.sh
      elif [[ "$CI_BUILD_TYPE" != "release-ready" ]] ; then
        docker exec --env MAKEFLAGS="-j5" --env EIO_MONITOR_POLL=1 $(cat $HOME/cid) .ci/build-efl-app.sh
      fi

after_success:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$DISTRO" != "" ]]; then
        docker login -u stefanschmidt1 -p "$DOCKER_PASSWORD"
        docker tag stefanschmidt1/ci-support-files:$DISTRO stefanschmidt1/ci-support-files:$DISTRO-$TRAVIS_BUILD_NUMBER
        docker push stefanschmidt1/ci-support-files:$DISTRO
        docker push stefanschmidt1/ci-support-files:$DISTRO-$TRAVIS_BUILD_NUMBER
      fi

notifications:
  irc:
    channels:
      - "chat.freenode.net#edevelop"
    on_success: change
    on_failure: always
    template:
      - "TravisCI build %{build_number} in branch %{branch}: %{result} - %{message}"
      - "Commit: %{commit_subject} (%{commit}) from %{author}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
