language: c

sudo: required
dist: trusty

os:
  - linux
  - osx

env:
  -
  - DISTRO=Ubuntu1710
  - DISTRO=Fedora27 CI_BUILD_TYPE=wayland
  - DISTRO=Fedora27 CI_BUILD_TYPE=misc
  - DISTRO=Fedora27 CI_BUILD_TYPE=misc-disabled
  - DISTRO=Debian91
  - DISTRO=Archlinux

services:
  - docker

matrix:
  fast_finish: true
  exclude:
    - os: osx
      env: DISTRO=Ubuntu1710
    - os: osx
      env: DISTRO=Fedora27 CI_BUILD_TYPE=wayland
    - os: osx
      env: DISTRO=Fedora27 CI_BUILD_TYPE=misc
    - os: osx
      env: DISTRO=Fedora27 CI_BUILD_TYPE=misc-disabled
    - os: osx
      env: DISTRO=Debian91
    - os: osx
      env: DISTRO=Archlinux
    - os: linux
      env:
  allow_failures:
    - os: osx
      env:

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then .ci/ci-osx-deps.sh ; fi

before_script:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$DISTRO" != "" ]]; then
        docker pull stefanschmidt1/ci-support-files:$DISTRO
      fi

script:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$DISTRO" != "" ]]; then
        docker run -v `pwd`:/src -w /src stefanschmidt1/ci-support-files:$DISTRO /src/.ci/ci-linux-build.sh $CI_BUILD_TYPE
      fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then .ci/ci-osx-build.sh ; fi

after_success:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$DISTRO" != "" ]]; then
        docker login -u stefanschmidt1 -p "$DOCKER_PASSWORD"
        docker tag stefanschmidt1/ci-support-files:$DISTRO stefanschmidt1/ci-support-files:$DISTRO-$TRAVIS_BUILD_NUMBER
        docker push stefanschmidt1/ci-support-files:$DISTRO
        docker push stefanschmidt1/ci-support-files:$DISTRO-$TRAVIS_BUILD_NUMBER
      fi
