apiRules:
- exclude:
    uidRegex: ^.*NativeInherit$
- exclude:
    uidRegex: ^.*NativeStruct$
- exclude:
    uidRegex: ^.*Concrete$
- include:
    uidRegex: ^Efl
- include:
    uidRegex: ^Eina
- exclude:
    uidRegex: ^.*
