/*
 * This is an automatically generated file using a python script.
 * ($EFL_HOME/src/utils/evas/generate_gl_thread_api.py)
 * Recommend that you modify data files ($EFL_HOME/src/utils/evas/gl_api_def.txt)
 * and make use of scripts if you need to fix them.
 */
extern GLenum (*glGetError_evgl_thread_cmd)(void);
extern void (*glVertexAttribPointer_evgl_thread_cmd)(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer);
extern void (*glEnableVertexAttribArray_evgl_thread_cmd)(GLuint index);
extern void (*glDisableVertexAttribArray_evgl_thread_cmd)(GLuint index);
extern void (*glDrawArrays_evgl_thread_cmd)(GLenum mode, GLint first, GLsizei count);
extern void (*glDrawElements_evgl_thread_cmd)(GLenum mode, GLsizei count, GLenum type, const void *indices);
extern void (*glGenBuffers_evgl_thread_cmd)(GLsizei n, GLuint *buffers);
extern void (*glDeleteBuffers_evgl_thread_cmd)(GLsizei n, const GLuint *buffers);
extern void (*glBindBuffer_evgl_thread_cmd)(GLenum target, GLuint buffer);
extern void (*glBufferData_evgl_thread_cmd)(GLenum target, GLsizeiptr size, const void *data, GLenum usage);
extern GLuint (*glCreateShader_evgl_thread_cmd)(GLenum type);
extern void (*glShaderSource_evgl_thread_cmd)(GLuint shader, GLsizei count, const GLchar **string, const GLint *length);
extern void (*glCompileShader_evgl_thread_cmd)(GLuint shader);
extern void (*glDeleteShader_evgl_thread_cmd)(GLuint shader);
extern GLuint (*glCreateProgram_evgl_thread_cmd)(void);
extern void (*glAttachShader_evgl_thread_cmd)(GLuint program, GLuint shader);
extern void (*glDetachShader_evgl_thread_cmd)(GLuint program, GLuint shader);
extern void (*glLinkProgram_evgl_thread_cmd)(GLuint program);
extern void (*glUseProgram_evgl_thread_cmd)(GLuint program);
extern void (*glDeleteProgram_evgl_thread_cmd)(GLuint program);
extern void (*glGetProgramBinary_orig_evgl_set)(void *func);
extern void *(*glGetProgramBinary_orig_evgl_get)(void);
extern void (*glGetProgramBinary_evgl_thread_cmd)(GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary);
extern void (*glProgramBinary_orig_evgl_set)(void *func);
extern void *(*glProgramBinary_orig_evgl_get)(void);
extern void (*glProgramBinary_evgl_thread_cmd)(GLuint program, GLenum binaryFormat, const void *binary, GLint length);
extern void (*glGetActiveAttrib_evgl_thread_cmd)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
extern GLint (*glGetAttribLocation_evgl_thread_cmd)(GLuint program, const GLchar *name);
extern void (*glBindAttribLocation_evgl_thread_cmd)(GLuint program, GLuint index, const GLchar *name);
extern GLint (*glGetUniformLocation_evgl_thread_cmd)(GLuint program, const GLchar *name);
extern void (*glUniform1f_evgl_thread_cmd)(GLint location, GLfloat v0);
extern void (*glUniform1i_evgl_thread_cmd)(GLint location, GLint v0);
extern void (*glUniform2f_evgl_thread_cmd)(GLint location, GLfloat v0, GLfloat v1);
extern void (*glUniform2i_evgl_thread_cmd)(GLint location, GLint v0, GLint v1);
extern void (*glUniform3f_evgl_thread_cmd)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
extern void (*glUniform3i_evgl_thread_cmd)(GLint location, GLint v0, GLint v1, GLint v2);
extern void (*glUniform4f_evgl_thread_cmd)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
extern void (*glUniform4i_evgl_thread_cmd)(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
extern void (*glUniform1fv_evgl_thread_cmd)(GLint location, GLsizei count, const GLfloat *value);
extern void (*glUniform1iv_evgl_thread_cmd)(GLint location, GLsizei count, const GLint *value);
extern void (*glUniform2fv_evgl_thread_cmd)(GLint location, GLsizei count, const GLfloat *value);
extern void (*glUniform2iv_evgl_thread_cmd)(GLint location, GLsizei count, const GLint *value);
extern void (*glUniform3fv_evgl_thread_cmd)(GLint location, GLsizei count, const GLfloat *value);
extern void (*glUniform3iv_evgl_thread_cmd)(GLint location, GLsizei count, const GLint *value);
extern void (*glUniform4fv_evgl_thread_cmd)(GLint location, GLsizei count, const GLfloat *value);
extern void (*glUniform4iv_evgl_thread_cmd)(GLint location, GLsizei count, const GLint *value);
extern void (*glUniformMatrix2fv_evgl_thread_cmd)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*glUniformMatrix3fv_evgl_thread_cmd)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*glUniformMatrix4fv_evgl_thread_cmd)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern void (*glViewport_evgl_thread_cmd)(GLint x, GLint y, GLsizei width, GLsizei height);
extern void (*glEnable_evgl_thread_cmd)(GLenum cap);
extern void (*glDisable_evgl_thread_cmd)(GLenum cap);
extern void (*glLineWidth_evgl_thread_cmd)(GLfloat width);
extern void (*glPolygonOffset_evgl_thread_cmd)(GLfloat factor, GLfloat units);
extern void (*glPixelStorei_evgl_thread_cmd)(GLenum pname, GLint param);
extern void (*glActiveTexture_evgl_thread_cmd)(GLenum texture);
extern void (*glGenTextures_evgl_thread_cmd)(GLsizei n, GLuint *textures);
extern void (*glBindTexture_evgl_thread_cmd)(GLenum target, GLuint texture);
extern void (*glDeleteTextures_evgl_thread_cmd)(GLsizei n, const GLuint *textures);
extern void (*glTexImage2D_evgl_thread_cmd)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels);
extern void (*glTexSubImage2D_evgl_thread_cmd)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
extern void (*glCompressedTexImage2D_evgl_thread_cmd)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data);
extern void (*glCompressedTexSubImage2D_evgl_thread_cmd)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data);
extern void (*glTexParameterf_evgl_thread_cmd)(GLenum target, GLenum pname, GLfloat param);
extern void (*glTexParameterfv_evgl_thread_cmd)(GLenum target, GLenum pname, const GLfloat *params);
extern void (*glTexParameteri_evgl_thread_cmd)(GLenum target, GLenum pname, GLint param);
extern void (*glTexParameteriv_evgl_thread_cmd)(GLenum target, GLenum pname, const GLint *params);
extern void (*glScissor_evgl_thread_cmd)(GLint x, GLint y, GLsizei width, GLsizei height);
extern void (*glBlendFunc_evgl_thread_cmd)(GLenum sfactor, GLenum dfactor);
extern void (*glBlendColor_evgl_thread_cmd)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void (*glDepthMask_evgl_thread_cmd)(GLboolean flag);
extern void (*glClear_evgl_thread_cmd)(GLbitfield mask);
extern void (*glClearColor_evgl_thread_cmd)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void (*glReadPixels_evgl_thread_cmd)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels);
extern void (*glGenFramebuffers_evgl_thread_cmd)(GLsizei n, GLuint *framebuffers);
extern void (*glBindFramebuffer_evgl_thread_cmd)(GLenum target, GLuint framebuffer);
extern void (*glDeleteFramebuffers_evgl_thread_cmd)(GLsizei n, const GLuint *framebuffers);
extern void (*glGenRenderbuffers_evgl_thread_cmd)(GLsizei n, GLuint *renderbuffers);
extern void (*glBindRenderbuffer_evgl_thread_cmd)(GLenum target, GLuint renderbuffer);
extern void (*glDeleteRenderbuffers_evgl_thread_cmd)(GLsizei n, const GLuint *renderbuffers);
extern void (*glRenderbufferStorage_evgl_thread_cmd)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
extern void (*glFramebufferRenderbuffer_evgl_thread_cmd)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
extern void (*glFramebufferTexture2D_evgl_thread_cmd)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
extern GLenum (*glCheckFramebufferStatus_evgl_thread_cmd)(GLenum target);
extern void (*glFlush_evgl_thread_cmd)(void);
extern void (*glFinish_evgl_thread_cmd)(void);
extern void (*glHint_evgl_thread_cmd)(GLenum target, GLenum mode);
extern const GLubyte * (*glGetString_evgl_thread_cmd)(GLenum name);
extern void (*glGetBooleanv_evgl_thread_cmd)(GLenum pname, GLboolean *data);
extern void (*glGetFloatv_evgl_thread_cmd)(GLenum pname, GLfloat *data);
extern void (*glGetIntegerv_evgl_thread_cmd)(GLenum pname, GLint *data);
extern GLboolean (*glIsBuffer_evgl_thread_cmd)(GLint buffer);
extern void (*glGetBufferParameteriv_evgl_thread_cmd)(GLenum target, GLenum pname, GLint *params);
extern GLboolean (*glIsShader_evgl_thread_cmd)(GLuint shader);
extern void (*glGetShaderiv_evgl_thread_cmd)(GLuint shader, GLenum pname, GLint *params);
extern void (*glGetAttachedShaders_evgl_thread_cmd)(GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders);
extern void (*glGetShaderInfoLog_evgl_thread_cmd)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
extern void (*glGetShaderSource_evgl_thread_cmd)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source);
extern void (*glGetShaderPrecisionFormat_evgl_thread_cmd)(GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision);
extern void (*glGetVertexAttribfv_evgl_thread_cmd)(GLuint index, GLenum pname, GLfloat *params);
extern void (*glGetVertexAttribiv_evgl_thread_cmd)(GLuint index, GLenum pname, GLint *params);
extern GLboolean (*glIsProgram_evgl_thread_cmd)(GLuint program);
extern void (*glGetProgramInfoLog_evgl_thread_cmd)(GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
extern void (*glGetProgramiv_evgl_thread_cmd)(GLuint program, GLenum pname, GLint *params);
extern GLboolean (*glIsFramebuffer_evgl_thread_cmd)(GLint framebuffer);
extern GLboolean (*glIsRenderbuffer_evgl_thread_cmd)(GLint renderbuffer);
extern void (*glGetRenderbufferParameteriv_evgl_thread_cmd)(GLenum target, GLenum pname, GLint *params);
extern GLboolean (*glIsTexture_evgl_thread_cmd)(GLint texture);


extern void _gl_thread_link_evgl_generated_init();
